cache: bundler
sudo: false
bundler_args: ""
rvm:
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
branches:
  only: master
script: "bundle exec rake spec"
matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails4.2.gemfile
